apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hr-workexp-abort
spec:
  destination:
    name: workexpdetails
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=hr)(;.*)?$"
  route:
  - labels:
      version: v1
  httpFault:
    abort:
      percent: 100
      httpStatus: 500
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: hr-finance-abort
spec:
  destination:
    name: financedetails
  precedence: 2
  match:
    request:
      headers:
        cookie:
          regex: "^(.*?;)?(user=hr)(;.*)?$"
  route:
  - labels:
      version: v1
  httpFault:
    abort:
      percent: 100
      httpStatus: 500