apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: reviews-test-v2
spec:
  destination:
    name: reviews
  precedence: 2
  match:
    request:
      headers:
        x-is-allowed:
          regex: "^(.*?;)?(true)(;.*)?$"
  route:
  - labels:
      version: v2