apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata: 
  name: reviews-foo-bar
spec: 
  destination: 
    name: reviews
  match: 
    request: 
      headers: 
        x-is-allowed:
          regex: ".*true.*"
  precedence: 2
  route: 
    - 
      labels: 
        version: v2
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata: 
  name: reviews-default
spec: 
  destination: 
    name: reviews
  precedence: 1
  route: 
    - 
      labels: 
        version: v3
      weight: 100